config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/profile/:id', to: 'static_pages#profile', as: 'profile'
  resources :posts do
    resources :comments
  end

  devise_for :users

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show]
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    require 'google/protobuf'
    require 'google/protobuf/well_known_types'
    require './protobuf_schemas/protobuf_schemas/comment_created_pb'

    @post = Post.find(params[:post_id])
    @comment = current_user.comments.create(comment_params_with_post)
    topic = "post.comment_created"

    msg = ProtobufSchemas::CommentCreated.new(
      post_id: Google::Protobuf::Int64Value.new(value: @post.id),
      user_id: Google::Protobuf::Int64Value.new(value: @comment.user.id),
      body: Google::Protobuf::StringValue.new(value: @comment.body),
      post_comment_count: Google::Protobuf::Int64Value.new(value: @post.comments.count)
    )

    encoded_msg = ProtobufSchemas::CommentCreated.encode(msg)

    DeliveryBoy.deliver_async(encoded_msg, topic: topic, key: @post.id)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    post = Post.find(@comment.post_id)
    topic = "comment.updated"

    value = {
      post_id: post.id,
      post_title: post.title,
      user_id: user.id,
      body: comment.body,
      likes: comment.likes
    }

    DeliveryBoy.deliver_async(value.to_json, topic: topic)

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params_with_post
      comment_params.merge(post: @post)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.fetch(:comment, {}).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post, {}).permit(:title, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:profile]

  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for [post, post.comments.new] do |form| %>
  <%= form_tag(post.comments.new[:body]) do %>
    <div class="comment-body-container">
      <p><%= form.text_area :body, cols: "80", rows: "2" %></p>
    </div>

    <div class="actions">
      <%= form.submit "Comment" %>
    </div>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar">
      <div class="link">
        <% if user_signed_in? %>
            <ul class="menu align-right">
              <li><%= link_to "Profile", profile_path(current_user) %></li>
              <li><%= link_to("Logout", destroy_user_session_path, method: :delete) %>
            </ul>
        <% else %>
          <ul class="menu align-right">
            <%= link_to "Log In", new_user_session_path %>
          </ul>
        <%  end %>
      </div>
    </div>
    
    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <div>
      <p>Title: <%= form.text_field :title %></p>
    </div>

    <div>
      <p><%= form.text_area :body, cols: "50", rows: "10" %></p>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% else %>
    <div>
      <p><%= link_to "Log in to create a new post", new_user_session_path %></p>
    </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= title "Entry Hall" %>

<div id="posts-index-container", class="grid-x">
  <% @posts.each do |post| %>
    <div class="post-link-container cell small-4 medium-4 large-4">
      <%= link_to post_path(post) do %>
        <h3><%= post.title %></h3>
        <h6><%= post.user.email %></h6>
      <% end %>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<%- title "New Post" %>

<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%- title @post.title %>

<div id="post-container">
  <div class="post-title-container">
    <h3><%= @post.title %></h3>
    <p><%= @post.user.email %></p>
  </div>

  <div class="post-body-container">
    <p><%= @post.body %></p>
  </div>
</div>

<div id="comment-container">
    <% @comments.each do |comment| %>
      <p class="show-comment-container"><%= comment.body %></p>
    <% end %>

  <%= render partial: 'comments/form', locals: { post: @post } %>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/static_pages/profile.html.erb
<div>
  <h2><%= current_user.email %></h2>
</div>